// <auto-generated />
using System;
using ConferenceBooking.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenceBooking.Infrastructure.Migrations
{
    [DbContext(typeof(ConferenceBookingContext))]
    partial class ConferenceBookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Finnish_Swedish_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.AddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("Money");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AddOns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coffee",
                            PricePerPerson = 20m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pastries",
                            PricePerPerson = 35m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fruit basket",
                            PricePerPerson = 25m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Water",
                            PricePerPerson = 10m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lunch catering",
                            PricePerPerson = 80m
                        });
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenceRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("Money");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceRoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.BookingAddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddOnId")
                        .HasColumnType("int");

                    b.Property<decimal>("BookedPricePerPerson")
                        .HasColumnType("Money");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddOnId");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingAddOns");
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.ConferenceRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("Money");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("ConferenceRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 12,
                            Number = "101",
                            PricePerHour = 1500m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 8,
                            Number = "102",
                            PricePerHour = 1000m
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 5,
                            Number = "103",
                            PricePerHour = 500m
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 30,
                            Number = "104",
                            PricePerHour = 3000m
                        });
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.RoomFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RoomFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Projector"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Whiteboard"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Video conferencing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ocean view"
                        });
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Role").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ConferenceRoomFeature", b =>
                {
                    b.Property<int>("ConferenceRoomId")
                        .HasColumnType("int");

                    b.Property<int>("RoomFeatureId")
                        .HasColumnType("int");

                    b.HasKey("ConferenceRoomId", "RoomFeatureId");

                    b.HasIndex("RoomFeatureId");

                    b.ToTable("ConferenceRoomFeatures", (string)null);

                    b.HasData(
                        new
                        {
                            ConferenceRoomId = 1,
                            RoomFeatureId = 1
                        },
                        new
                        {
                            ConferenceRoomId = 1,
                            RoomFeatureId = 2
                        },
                        new
                        {
                            ConferenceRoomId = 1,
                            RoomFeatureId = 3
                        },
                        new
                        {
                            ConferenceRoomId = 1,
                            RoomFeatureId = 4
                        },
                        new
                        {
                            ConferenceRoomId = 2,
                            RoomFeatureId = 1
                        },
                        new
                        {
                            ConferenceRoomId = 2,
                            RoomFeatureId = 3
                        },
                        new
                        {
                            ConferenceRoomId = 2,
                            RoomFeatureId = 4
                        },
                        new
                        {
                            ConferenceRoomId = 3,
                            RoomFeatureId = 2
                        },
                        new
                        {
                            ConferenceRoomId = 4,
                            RoomFeatureId = 1
                        });
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.Admin", b =>
                {
                    b.HasBaseType("ConferenceBooking.Domain.Entities.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.Employee", b =>
                {
                    b.HasBaseType("ConferenceBooking.Domain.Entities.User");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.ExternalUser", b =>
                {
                    b.HasBaseType("ConferenceBooking.Domain.Entities.User");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasDiscriminator().HasValue("ExternalUser");
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.Booking", b =>
                {
                    b.HasOne("ConferenceBooking.Domain.Entities.ConferenceRoom", "ConferenceRoom")
                        .WithMany("Bookings")
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConferenceBooking.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConferenceRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.BookingAddOn", b =>
                {
                    b.HasOne("ConferenceBooking.Domain.Entities.AddOn", "AddOn")
                        .WithMany("BookingAddOns")
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConferenceBooking.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingAddOns")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("ConferenceRoomFeature", b =>
                {
                    b.HasOne("ConferenceBooking.Domain.Entities.ConferenceRoom", null)
                        .WithMany()
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceBooking.Domain.Entities.RoomFeature", null)
                        .WithMany()
                        .HasForeignKey("RoomFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.AddOn", b =>
                {
                    b.Navigation("BookingAddOns");
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingAddOns");
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.ConferenceRoom", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("ConferenceBooking.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
